apiVersion: v1
kind: Pod
metadata:
  name: ex0
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "while true; do echo Hello from Alpine; sleep 3600; done"]
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
        limits:
          cpu: "50m"
          memory: "32Mi"
    - name: container_nginx
      image: nginx
      resources:
        requests:
          memory: "32Mi"
          cpu: "20m"
        limits:
          cpu: "100m"
          memory: "64Mi"
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello from Busybox; sleep 3600; done"]
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
        limits:
          cpu: "50m"
          memory: "32Mi"